include: package:lints/recommended.yaml
analyzer:
  language:
    strict-casts: true
    strict-raw-types: true
  exclude:
    - test/invalid_schemas.dart
    - test/schema_validation.dart
# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
