include: package:flutter_lints/flutter.yaml
analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  exclude:
    - test/invalid_schemas.dart
    - test/schema_validation.dart
# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
